### PR TITLE
Change Processes to classes and add an inheritance relationship betwe…

### PR DESCRIPTION
**Pull request by austinschneider**
…en PhysicalProcess and InjectionProcess

### CODE REVIEW

**Comment by austinschneider** [comment]
I think this is good to go now

**Review by nickkamp1 — COMMENTED** [review]
Code changes look reasonable. I think this might require some updates to LIController. I will test locally and re-review

**Comment by austinschneider** [comment]
> Code changes look reasonable. I think this might require some updates to LIController. I will test locally and re-review

I think the main issue is going to be the `SetCrossSections` method that I removed from the pybindings. I can either add it back in or `LIController` can just use the property access to `cross_sections`.

**Comment by nickkamp1** [comment]
> > Code changes look reasonable. I think this might require some updates to LIController. I will test locally and re-review
> 
> I think the main issue is going to be the `SetCrossSections` method that I removed from the pybindings. I can either add it back in or `LIController` can just use the property access to `cross_sections`. Otherwise I don't see any problems in `LiController`.

Updating LIController to just access cross_sections, I think that's cleaner

**Review by nickkamp1 — APPROVED** [review]
this looks good to go now!

**Pull request merged**
